### ISSUE TITLE
mfqe panics if sequence name list contains empty line

### ISSUE THREAD

**Issue by apcamargo** [wwood/mfqe#16]
Hi Ben!

I executed `mfqe` using a sequence name list file that contained 41 sequence names and a empty line at the end (automatically added by vim). I got the following error:

```
[2021-01-10T19:44:53Z INFO  mfqe] Read in 42 read names from gene_list.txt
[2021-01-10T19:44:53Z INFO  mfqe] Iterating input FASTQ file
[2021-01-10T19:44:53Z INFO  mfqe] Extracted 41 reads from 15484 total
thread 'main' panicked at 'Mismatching numbers of read names were observed. Expected:
[42]
but found
[41]', src/main.rs:333:9
```

The output FASTA was correct, nonetheless.

**Comment by wwood** [comment]
Hi,

I'm actually surprised vim adds an empty line, are you sure about that? A newline at the end of the file, sure, but not a whole line I don't think. Either way that commit above means empty lines are ignored now.

**Comment by apcamargo** [comment]
My bad, it was [Micro](https://micro-editor.github.io/) that did that.

Thanks for the fix!!!
